use crate::lockfile::Lockfile;
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

const SKILLS_MD: &str = "SKILLS.md";
const AGENTS_MD: &str = "AGENTS.md";
const APM_BLOCK_START: &str = "<!-- apm:skills -->";
const APM_BLOCK_END: &str = "<!-- /apm:skills -->";

/// Entry representing an installed skill for the manifest.
pub struct SkillEntry {
    pub scope: String,
    pub name: String,
    pub description: String,
    pub kind: String,
    pub tags: Vec<String>,
}

/// Regenerate SKILLS.md from installed skills.
pub fn regenerate_skills_md(root: &Path, entries: &[SkillEntry]) -> Result<()> {
    let path = root.join(SKILLS_MD);

    if entries.is_empty() {
        // Remove SKILLS.md if no skills installed
        if path.exists() {
            fs::remove_file(&path)?;
        }
        return Ok(());
    }

    let mut content = String::from("# Installed Skills\n\n");
    content.push_str("<!-- This file is auto-generated by APM. Do not edit manually. -->\n\n");

    for entry in entries {
        content.push_str(&format!("## @{}/{}\n\n", entry.scope, entry.name));
        content.push_str(&format!("- **Kind:** {}\n", entry.kind));
        content.push_str(&format!("- **Description:** {}\n", entry.description));
        if !entry.tags.is_empty() {
            content.push_str(&format!("- **Tags:** {}\n", entry.tags.join(", ")));
        }
        content.push_str(&format!(
            "- **Path:** .skills/{}/{}/SKILL.md\n",
            entry.scope, entry.name
        ));
        content.push('\n');
    }

    fs::write(&path, content)?;
    Ok(())
}

/// Ensure AGENTS.md exists and contains a reference to SKILLS.md.
pub fn ensure_agents_md(root: &Path) -> Result<()> {
    let path = root.join(AGENTS_MD);

    if !path.exists() {
        let content = format!(
            "# Agent Configuration\n\
            \n\
            {start}\n\
            This project uses [APM](https://apm.orthg.nl) to manage agent skills.\n\
            See [SKILLS.md](./SKILLS.md) for all installed skills and their descriptions.\n\
            {end}\n",
            start = APM_BLOCK_START,
            end = APM_BLOCK_END,
        );
        fs::write(&path, content)?;
        return Ok(());
    }

    // File exists — check if it already has the APM block
    let existing = fs::read_to_string(&path)?;
    if existing.contains(APM_BLOCK_START) {
        return Ok(());
    }

    // Append the APM block
    let mut content = existing;
    if !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(&format!(
        "\n{start}\n\
        This project uses [APM](https://apm.orthg.nl) to manage agent skills.\n\
        See [SKILLS.md](./SKILLS.md) for all installed skills and their descriptions.\n\
        {end}\n",
        start = APM_BLOCK_START,
        end = APM_BLOCK_END,
    ));
    fs::write(&path, content)?;

    Ok(())
}

/// Build skill entries from the lockfile + installed SKILL.md frontmatter.
pub fn build_entries_from_lockfile(root: &Path) -> Result<Vec<SkillEntry>> {
    let lockfile = Lockfile::load(root)?;
    let mut entries = Vec::new();

    for full_name in lockfile.packages.keys() {
        let stripped = full_name.strip_prefix('@').unwrap_or(full_name);
        let parts: Vec<&str> = stripped.splitn(2, '/').collect();
        if parts.len() != 2 {
            continue;
        }
        let (scope, name) = (parts[0], parts[1]);

        let skill_path = root.join(".skills").join(scope).join(name).join("SKILL.md");
        let (description, kind, tags) = if skill_path.exists() {
            parse_skill_frontmatter(&skill_path)
        } else {
            (String::new(), String::from("skill"), Vec::new())
        };

        entries.push(SkillEntry {
            scope: scope.to_string(),
            name: name.to_string(),
            description,
            kind,
            tags,
        });
    }

    Ok(entries)
}

/// Parse description, kind, and tags from SKILL.md frontmatter.
fn parse_skill_frontmatter(path: &Path) -> (String, String, Vec<String>) {
    let content = match fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => return (String::new(), String::from("skill"), Vec::new()),
    };

    let fm = match extract_frontmatter(&content) {
        Some(fm) => fm,
        None => return (String::new(), String::from("skill"), Vec::new()),
    };

    let yaml: serde_yaml::Value = match serde_yaml::from_str(&fm) {
        Ok(v) => v,
        Err(_) => return (String::new(), String::from("skill"), Vec::new()),
    };

    let description = yaml
        .get("description")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let kind = yaml
        .get("kind")
        .and_then(|v| v.as_str())
        .unwrap_or("skill")
        .to_string();

    let tags = yaml
        .get("tags")
        .and_then(|v| v.as_sequence())
        .map(|seq| {
            seq.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    (description, kind, tags)
}

fn extract_frontmatter(content: &str) -> Option<String> {
    let trimmed = content.trim_start();
    if !trimmed.starts_with("---") {
        return None;
    }
    let after_first = &trimmed[3..];
    let end = after_first.find("---")?;
    Some(after_first[..end].to_string())
}
